ignore:
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "**/*.mocks.dart"
  - "**/build/**"
  - "**/.dart_tool/**"
  - "**/test-results/**"
  - "**/coverage/**"

coverage:
  status:
    project:
      default:
        target: 0%
        threshold: 0%
        informational: true
        branches:
          - dev
      feature:
        target: 0%
        threshold: 0%
        informational: true
        branches:
          - feature
          - "feature/.*"
      newdev:
        target: 0%
        threshold: 0%
        informational: true
        branches:
          - newdev
      main:
        target: 0%
        threshold: 0%
        informational: true
        branches:
          - main
    patch:
      default:
        target: 0%
        threshold: 0%
        informational: true
        branches:
          - dev
      feature:
        target: 0%
        threshold: 0%
        informational: true
        branches:
          - feature
          - "feature/.*"
      newdev:
        target: 0%
        threshold: 0%
        informational: true
        branches:
          - newdev
      main:
        target: 0%
        threshold: 0%
        informational: true
        branches:
          - main

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
