sonar.projectKey=COS301-SE-2026_Mobile-Budgeting-App
sonar.organization=cos301-se-2026
sonar.projectName=Mobile-Budgeting-App

sonar.sources=Flutter/budgetit/lib
sonar.tests=Flutter/budgetit/test
sonar.sourceEncoding=UTF-8

sonar.dart.lcov.reportPaths=Flutter/budgetit/coverage/lcov.info
