// Mocks generated by Mockito from annotations
// in budgetit/test/unit/analysis/background_anomaly_scanner_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;

import 'package:budgetit/database/app_database.dart' as _i10;
import 'package:budgetit/database/daos/budget_dao.dart' as _i6;
import 'package:budgetit/database/daos/category_dao.dart' as _i3;
import 'package:budgetit/database/daos/embedding_cache_dao.dart' as _i4;
import 'package:budgetit/database/daos/recurring_transaction_dao.dart' as _i7;
import 'package:budgetit/database/daos/schema_cache_dao.dart' as _i9;
import 'package:budgetit/database/daos/settings_dao.dart' as _i8;
import 'package:budgetit/database/daos/transaction_dao.dart' as _i5;
import 'package:budgetit/database/schema.dart' as _i16;
import 'package:decimal/decimal.dart' as _i15;
import 'package:drift/backends.dart' as _i11;
import 'package:drift/drift.dart' as _i2;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i12;
import 'package:flutter/widgets.dart' as _i17;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMigrationStrategy_0 extends _i1.SmartFake
    implements _i2.MigrationStrategy {
  _FakeMigrationStrategy_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoryDao_1 extends _i1.SmartFake implements _i3.CategoryDao {
  _FakeCategoryDao_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEmbeddingCacheDao_2 extends _i1.SmartFake
    implements _i4.EmbeddingCacheDao {
  _FakeEmbeddingCacheDao_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransactionDao_3 extends _i1.SmartFake
    implements _i5.TransactionDao {
  _FakeTransactionDao_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBudgetDao_4 extends _i1.SmartFake implements _i6.BudgetDao {
  _FakeBudgetDao_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecurringTransactionDao_5 extends _i1.SmartFake
    implements _i7.RecurringTransactionDao {
  _FakeRecurringTransactionDao_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSettingsDao_6 extends _i1.SmartFake implements _i8.SettingsDao {
  _FakeSettingsDao_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSchemaCacheDao_7 extends _i1.SmartFake
    implements _i9.SchemaCacheDao {
  _FakeSchemaCacheDao_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AppDatabaseManager_8 extends _i1.SmartFake
    implements _i10.$AppDatabaseManager {
  _Fake$AppDatabaseManager_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$CategoriesTable_9 extends _i1.SmartFake
    implements _i10.$CategoriesTable {
  _Fake$CategoriesTable_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$CategoryClosureTable_10 extends _i1.SmartFake
    implements _i10.$CategoryClosureTable {
  _Fake$CategoryClosureTable_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$RecurringTransactionsTable_11 extends _i1.SmartFake
    implements _i10.$RecurringTransactionsTable {
  _Fake$RecurringTransactionsTable_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _Fake$ImportsTable_12 extends _i1.SmartFake
    implements _i10.$ImportsTable {
  _Fake$ImportsTable_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$TransactionsTable_13 extends _i1.SmartFake
    implements _i10.$TransactionsTable {
  _Fake$TransactionsTable_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$TransactionCategoryMapTable_14 extends _i1.SmartFake
    implements _i10.$TransactionCategoryMapTable {
  _Fake$TransactionCategoryMapTable_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _Fake$BudgetTemplatesTable_15 extends _i1.SmartFake
    implements _i10.$BudgetTemplatesTable {
  _Fake$BudgetTemplatesTable_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$BudgetPeriodsTable_16 extends _i1.SmartFake
    implements _i10.$BudgetPeriodsTable {
  _Fake$BudgetPeriodsTable_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AppSettingsTable_17 extends _i1.SmartFake
    implements _i10.$AppSettingsTable {
  _Fake$AppSettingsTable_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$EmbeddingCacheEntriesTable_18 extends _i1.SmartFake
    implements _i10.$EmbeddingCacheEntriesTable {
  _Fake$EmbeddingCacheEntriesTable_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _Fake$StatementSchemaCacheTable_19 extends _i1.SmartFake
    implements _i10.$StatementSchemaCacheTable {
  _Fake$StatementSchemaCacheTable_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_20 extends _i1.SmartFake
    implements _i2.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeneratedDatabase_21 extends _i1.SmartFake
    implements _i2.GeneratedDatabase {
  _FakeGeneratedDatabase_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryUpdateRules_22 extends _i1.SmartFake
    implements _i2.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_23 extends _i1.SmartFake
    implements _i2.DatabaseConnection {
  _FakeDatabaseConnection_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_24 extends _i1.SmartFake
    implements _i11.QueryExecutor {
  _FakeQueryExecutor_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_25 extends _i1.SmartFake
    implements _i12.StreamQueryStore {
  _FakeStreamQueryStore_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_26 extends _i1.SmartFake
    implements _i2.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrator_27 extends _i1.SmartFake implements _i2.Migrator {
  _FakeMigrator_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_28<T> extends _i1.SmartFake implements _i13.Future<T> {
  _FakeFuture_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_29<T1 extends _i2.Table, D1> extends _i1.SmartFake
    implements _i2.InsertStatement<T1, D1> {
  _FakeInsertStatement_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_30<T extends _i2.Table, D> extends _i1.SmartFake
    implements _i2.UpdateStatement<T, D> {
  _FakeUpdateStatement_30(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_31<T1 extends _i2.HasResultSet, D>
    extends _i1.SmartFake
    implements _i2.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_31(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_32<FirstT extends _i2.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i2.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_32(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_33<Row> extends _i1.SmartFake
    implements _i2.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_33(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_34<T1 extends _i2.Table, D1> extends _i1.SmartFake
    implements _i2.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_34(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_35<T> extends _i1.SmartFake implements _i2.Selectable<T> {
  _FakeSelectable_35(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_36 extends _i1.SmartFake
    implements _i2.GenerationContext {
  _FakeGenerationContext_36(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppDatabase_37 extends _i1.SmartFake implements _i10.AppDatabase {
  _FakeAppDatabase_37(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransactionDaoManager_38 extends _i1.SmartFake
    implements _i5.TransactionDaoManager {
  _FakeTransactionDaoManager_38(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransaction_39 extends _i1.SmartFake implements _i10.Transaction {
  _FakeTransaction_39(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransactionCategoryMapData_40 extends _i1.SmartFake
    implements _i10.TransactionCategoryMapData {
  _FakeTransactionCategoryMapData_40(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoryDaoManager_41 extends _i1.SmartFake
    implements _i3.CategoryDaoManager {
  _FakeCategoryDaoManager_41(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategory_42 extends _i1.SmartFake implements _i10.Category {
  _FakeCategory_42(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i10.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion =>
      (super.noSuchMethod(Invocation.getter(#schemaVersion), returnValue: 0)
          as int);

  @override
  _i2.MigrationStrategy get migration =>
      (super.noSuchMethod(
            Invocation.getter(#migration),
            returnValue: _FakeMigrationStrategy_0(
              this,
              Invocation.getter(#migration),
            ),
          )
          as _i2.MigrationStrategy);

  @override
  _i3.CategoryDao get categoryDao =>
      (super.noSuchMethod(
            Invocation.getter(#categoryDao),
            returnValue: _FakeCategoryDao_1(
              this,
              Invocation.getter(#categoryDao),
            ),
          )
          as _i3.CategoryDao);

  @override
  _i4.EmbeddingCacheDao get embeddingCacheDao =>
      (super.noSuchMethod(
            Invocation.getter(#embeddingCacheDao),
            returnValue: _FakeEmbeddingCacheDao_2(
              this,
              Invocation.getter(#embeddingCacheDao),
            ),
          )
          as _i4.EmbeddingCacheDao);

  @override
  _i5.TransactionDao get transactionDao =>
      (super.noSuchMethod(
            Invocation.getter(#transactionDao),
            returnValue: _FakeTransactionDao_3(
              this,
              Invocation.getter(#transactionDao),
            ),
          )
          as _i5.TransactionDao);

  @override
  _i6.BudgetDao get budgetDao =>
      (super.noSuchMethod(
            Invocation.getter(#budgetDao),
            returnValue: _FakeBudgetDao_4(this, Invocation.getter(#budgetDao)),
          )
          as _i6.BudgetDao);

  @override
  _i7.RecurringTransactionDao get recurringTransactionDao =>
      (super.noSuchMethod(
            Invocation.getter(#recurringTransactionDao),
            returnValue: _FakeRecurringTransactionDao_5(
              this,
              Invocation.getter(#recurringTransactionDao),
            ),
          )
          as _i7.RecurringTransactionDao);

  @override
  _i8.SettingsDao get settingsDao =>
      (super.noSuchMethod(
            Invocation.getter(#settingsDao),
            returnValue: _FakeSettingsDao_6(
              this,
              Invocation.getter(#settingsDao),
            ),
          )
          as _i8.SettingsDao);

  @override
  _i9.SchemaCacheDao get schemaCacheDao =>
      (super.noSuchMethod(
            Invocation.getter(#schemaCacheDao),
            returnValue: _FakeSchemaCacheDao_7(
              this,
              Invocation.getter(#schemaCacheDao),
            ),
          )
          as _i9.SchemaCacheDao);

  @override
  _i10.$AppDatabaseManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _Fake$AppDatabaseManager_8(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i10.$AppDatabaseManager);

  @override
  _i10.$CategoriesTable get categories =>
      (super.noSuchMethod(
            Invocation.getter(#categories),
            returnValue: _Fake$CategoriesTable_9(
              this,
              Invocation.getter(#categories),
            ),
          )
          as _i10.$CategoriesTable);

  @override
  _i10.$CategoryClosureTable get categoryClosure =>
      (super.noSuchMethod(
            Invocation.getter(#categoryClosure),
            returnValue: _Fake$CategoryClosureTable_10(
              this,
              Invocation.getter(#categoryClosure),
            ),
          )
          as _i10.$CategoryClosureTable);

  @override
  _i10.$RecurringTransactionsTable get recurringTransactions =>
      (super.noSuchMethod(
            Invocation.getter(#recurringTransactions),
            returnValue: _Fake$RecurringTransactionsTable_11(
              this,
              Invocation.getter(#recurringTransactions),
            ),
          )
          as _i10.$RecurringTransactionsTable);

  @override
  _i10.$ImportsTable get imports =>
      (super.noSuchMethod(
            Invocation.getter(#imports),
            returnValue: _Fake$ImportsTable_12(
              this,
              Invocation.getter(#imports),
            ),
          )
          as _i10.$ImportsTable);

  @override
  _i10.$TransactionsTable get transactions =>
      (super.noSuchMethod(
            Invocation.getter(#transactions),
            returnValue: _Fake$TransactionsTable_13(
              this,
              Invocation.getter(#transactions),
            ),
          )
          as _i10.$TransactionsTable);

  @override
  _i10.$TransactionCategoryMapTable get transactionCategoryMap =>
      (super.noSuchMethod(
            Invocation.getter(#transactionCategoryMap),
            returnValue: _Fake$TransactionCategoryMapTable_14(
              this,
              Invocation.getter(#transactionCategoryMap),
            ),
          )
          as _i10.$TransactionCategoryMapTable);

  @override
  _i10.$BudgetTemplatesTable get budgetTemplates =>
      (super.noSuchMethod(
            Invocation.getter(#budgetTemplates),
            returnValue: _Fake$BudgetTemplatesTable_15(
              this,
              Invocation.getter(#budgetTemplates),
            ),
          )
          as _i10.$BudgetTemplatesTable);

  @override
  _i10.$BudgetPeriodsTable get budgetPeriods =>
      (super.noSuchMethod(
            Invocation.getter(#budgetPeriods),
            returnValue: _Fake$BudgetPeriodsTable_16(
              this,
              Invocation.getter(#budgetPeriods),
            ),
          )
          as _i10.$BudgetPeriodsTable);

  @override
  _i10.$AppSettingsTable get appSettings =>
      (super.noSuchMethod(
            Invocation.getter(#appSettings),
            returnValue: _Fake$AppSettingsTable_17(
              this,
              Invocation.getter(#appSettings),
            ),
          )
          as _i10.$AppSettingsTable);

  @override
  _i10.$EmbeddingCacheEntriesTable get embeddingCacheEntries =>
      (super.noSuchMethod(
            Invocation.getter(#embeddingCacheEntries),
            returnValue: _Fake$EmbeddingCacheEntriesTable_18(
              this,
              Invocation.getter(#embeddingCacheEntries),
            ),
          )
          as _i10.$EmbeddingCacheEntriesTable);

  @override
  _i10.$StatementSchemaCacheTable get statementSchemaCache =>
      (super.noSuchMethod(
            Invocation.getter(#statementSchemaCache),
            returnValue: _Fake$StatementSchemaCacheTable_19(
              this,
              Invocation.getter(#statementSchemaCache),
            ),
          )
          as _i10.$StatementSchemaCacheTable);

  @override
  Iterable<_i2.TableInfo<_i2.Table, Object?>> get allTables =>
      (super.noSuchMethod(
            Invocation.getter(#allTables),
            returnValue: <_i2.TableInfo<_i2.Table, Object?>>[],
          )
          as Iterable<_i2.TableInfo<_i2.Table, Object?>>);

  @override
  List<_i2.DatabaseSchemaEntity> get allSchemaEntities =>
      (super.noSuchMethod(
            Invocation.getter(#allSchemaEntities),
            returnValue: <_i2.DatabaseSchemaEntity>[],
          )
          as List<_i2.DatabaseSchemaEntity>);

  @override
  _i2.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_20(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i2.DriftDatabaseOptions);

  @override
  _i2.GeneratedDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeGeneratedDatabase_21(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i2.GeneratedDatabase);

  @override
  _i2.StreamQueryUpdateRules get streamUpdateRules =>
      (super.noSuchMethod(
            Invocation.getter(#streamUpdateRules),
            returnValue: _FakeStreamQueryUpdateRules_22(
              this,
              Invocation.getter(#streamUpdateRules),
            ),
          )
          as _i2.StreamQueryUpdateRules);

  @override
  _i2.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_23(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i2.DatabaseConnection);

  @override
  _i2.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i14.dummyValue<_i2.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i2.SqlTypes);

  @override
  _i11.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_24(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i11.QueryExecutor);

  @override
  _i12.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_25(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i12.StreamQueryStore);

  @override
  _i2.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_26(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i2.DatabaseConnectionUser);

  @override
  _i2.Migrator createMigrator() =>
      (super.noSuchMethod(
            Invocation.method(#createMigrator, []),
            returnValue: _FakeMigrator_27(
              this,
              Invocation.method(#createMigrator, []),
            ),
          )
          as _i2.Migrator);

  @override
  _i13.Future<void> beforeOpen(
    _i11.QueryExecutor? executor,
    _i2.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#beforeOpen, [executor, details]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<Ret> computeWithDatabase<Ret, DB extends _i2.GeneratedDatabase>({
    required _i13.FutureOr<Ret> Function(DB)? computation,
    required DB Function(_i2.DatabaseConnection)? connect,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#computeWithDatabase, [], {
              #computation: computation,
              #connect: connect,
            }),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<Ret>(
                    this,
                    Invocation.method(#computeWithDatabase, [], {
                      #computation: computation,
                      #connect: connect,
                    }),
                  ),
                  (Ret v) => _i13.Future<Ret>.value(v),
                ) ??
                _FakeFuture_28<Ret>(
                  this,
                  Invocation.method(#computeWithDatabase, [], {
                    #computation: computation,
                    #connect: connect,
                  }),
                ),
          )
          as _i13.Future<Ret>);

  @override
  _i13.Stream<T> createStream<T extends Object>(
    _i12.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i13.Stream<T>.empty(),
          )
          as _i13.Stream<T>);

  @override
  T alias<T, D>(_i2.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i14.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i2.TableInfo<_i2.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i2.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Stream<Set<_i2.TableUpdate>> tableUpdates([
    _i2.TableUpdateQuery? query = const _i2.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i13.Stream<Set<_i2.TableUpdate>>.empty(),
          )
          as _i13.Stream<Set<_i2.TableUpdate>>);

  @override
  _i13.Future<T> doWhenOpened<T>(
    _i13.FutureOr<T> Function(_i11.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i13.Future<T>.value(v),
                ) ??
                _FakeFuture_28<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i13.Future<T>);

  @override
  _i2.InsertStatement<T, D> into<T extends _i2.Table, D>(
    _i2.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_29<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i2.InsertStatement<T, D>);

  @override
  _i2.UpdateStatement<Tbl, R> update<Tbl extends _i2.Table, R>(
    _i2.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_30<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i2.UpdateStatement<Tbl, R>);

  @override
  _i2.SimpleSelectStatement<T, R> select<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_31<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i2.SimpleSelectStatement<T, R>);

  @override
  _i2.JoinedSelectStatement<T, R> selectOnly<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_32<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i2.JoinedSelectStatement<T, R>);

  @override
  _i2.BaseSelectStatement<_i2.TypedResult> selectExpressions(
    Iterable<_i2.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_33<_i2.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i2.BaseSelectStatement<_i2.TypedResult>);

  @override
  _i2.DeleteStatement<T, D> delete<T extends _i2.Table, D>(
    _i2.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_34<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i2.DeleteStatement<T, D>);

  @override
  _i13.Future<int> customUpdate(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i13.Future<int>.value(0),
          )
          as _i13.Future<int>);

  @override
  _i13.Future<int> customInsert(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i13.Future<int>.value(0),
          )
          as _i13.Future<int>);

  @override
  _i13.Future<List<_i2.QueryRow>> customWriteReturning(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i13.Future<List<_i2.QueryRow>>.value(
              <_i2.QueryRow>[],
            ),
          )
          as _i13.Future<List<_i2.QueryRow>>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelect(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_35<_i2.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i2.Selectable<_i2.QueryRow>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelectQuery(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_35<_i2.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i2.Selectable<_i2.QueryRow>);

  @override
  _i13.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<T> transaction<T>(
    _i13.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i13.Future<T>.value(v),
                ) ??
                _FakeFuture_28<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i13.Future<T>);

  @override
  _i13.Future<T> exclusively<T>(_i13.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i13.Future<T>.value(v),
                ) ??
                _FakeFuture_28<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i13.Future<T>);

  @override
  _i13.Future<void> batch(
    _i13.FutureOr<void> Function(_i2.Batch)? runInBatch,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<T> runWithInterceptor<T>(
    _i13.Future<T> Function()? action, {
    required _i2.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i13.Future<T>.value(v),
                ) ??
                _FakeFuture_28<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i13.Future<T>);

  @override
  _i2.GenerationContext $write(
    _i2.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_36(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i2.GenerationContext);

  @override
  _i2.GenerationContext $writeInsertable(
    _i2.TableInfo<_i2.Table, dynamic>? table,
    _i2.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_36(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i2.GenerationContext);

  @override
  _i2.GenerationContext $writeUpdateInsertable(
    _i2.TableInfo<_i2.Table, dynamic>? table,
    _i2.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeUpdateInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_36(
              this,
              Invocation.method(
                #$writeUpdateInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i2.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);
}

/// A class which mocks [TransactionDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionDao extends _i1.Mock implements _i5.TransactionDao {
  MockTransactionDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.AppDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeAppDatabase_37(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i10.AppDatabase);

  @override
  _i2.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_23(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i2.DatabaseConnection);

  @override
  _i2.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_20(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i2.DriftDatabaseOptions);

  @override
  _i2.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i14.dummyValue<_i2.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i2.SqlTypes);

  @override
  _i11.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_24(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i11.QueryExecutor);

  @override
  _i12.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_25(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i12.StreamQueryStore);

  @override
  _i2.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_26(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i2.DatabaseConnectionUser);

  @override
  _i10.$CategoriesTable get categories =>
      (super.noSuchMethod(
            Invocation.getter(#categories),
            returnValue: _Fake$CategoriesTable_9(
              this,
              Invocation.getter(#categories),
            ),
          )
          as _i10.$CategoriesTable);

  @override
  _i10.$RecurringTransactionsTable get recurringTransactions =>
      (super.noSuchMethod(
            Invocation.getter(#recurringTransactions),
            returnValue: _Fake$RecurringTransactionsTable_11(
              this,
              Invocation.getter(#recurringTransactions),
            ),
          )
          as _i10.$RecurringTransactionsTable);

  @override
  _i10.$ImportsTable get imports =>
      (super.noSuchMethod(
            Invocation.getter(#imports),
            returnValue: _Fake$ImportsTable_12(
              this,
              Invocation.getter(#imports),
            ),
          )
          as _i10.$ImportsTable);

  @override
  _i10.$TransactionsTable get transactions =>
      (super.noSuchMethod(
            Invocation.getter(#transactions),
            returnValue: _Fake$TransactionsTable_13(
              this,
              Invocation.getter(#transactions),
            ),
          )
          as _i10.$TransactionsTable);

  @override
  _i10.$TransactionCategoryMapTable get transactionCategoryMap =>
      (super.noSuchMethod(
            Invocation.getter(#transactionCategoryMap),
            returnValue: _Fake$TransactionCategoryMapTable_14(
              this,
              Invocation.getter(#transactionCategoryMap),
            ),
          )
          as _i10.$TransactionCategoryMapTable);

  @override
  _i5.TransactionDaoManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _FakeTransactionDaoManager_38(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i5.TransactionDaoManager);

  @override
  _i13.Future<_i10.Transaction> insertTransaction({
    required _i15.Decimal? amount,
    required _i16.TransactionType? type,
    required String? shortDescription,
    String? longDescription,
    required DateTime? transactionDate,
    required _i16.TransactionSource? source,
    String? currency = 'ZAR',
    String? recurringId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertTransaction, [], {
              #amount: amount,
              #type: type,
              #shortDescription: shortDescription,
              #longDescription: longDescription,
              #transactionDate: transactionDate,
              #source: source,
              #currency: currency,
              #recurringId: recurringId,
            }),
            returnValue: _i13.Future<_i10.Transaction>.value(
              _FakeTransaction_39(
                this,
                Invocation.method(#insertTransaction, [], {
                  #amount: amount,
                  #type: type,
                  #shortDescription: shortDescription,
                  #longDescription: longDescription,
                  #transactionDate: transactionDate,
                  #source: source,
                  #currency: currency,
                  #recurringId: recurringId,
                }),
              ),
            ),
          )
          as _i13.Future<_i10.Transaction>);

  @override
  _i13.Future<_i10.Transaction?> getTransactionById(
    String? id, {
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getTransactionById,
              [id],
              {#includeDeleted: includeDeleted},
            ),
            returnValue: _i13.Future<_i10.Transaction?>.value(),
          )
          as _i13.Future<_i10.Transaction?>);

  @override
  _i13.Future<List<_i10.Transaction>> getAllTransactions({
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllTransactions, [], {
              #includeDeleted: includeDeleted,
            }),
            returnValue: _i13.Future<List<_i10.Transaction>>.value(
              <_i10.Transaction>[],
            ),
          )
          as _i13.Future<List<_i10.Transaction>>);

  @override
  _i13.Future<List<_i10.Transaction>> getTransactionsByType(
    _i16.TransactionType? type, {
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getTransactionsByType,
              [type],
              {#includeDeleted: includeDeleted},
            ),
            returnValue: _i13.Future<List<_i10.Transaction>>.value(
              <_i10.Transaction>[],
            ),
          )
          as _i13.Future<List<_i10.Transaction>>);

  @override
  _i13.Future<List<_i10.Transaction>> getTransactionsByDateRange(
    DateTime? start,
    DateTime? end, {
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getTransactionsByDateRange,
              [start, end],
              {#includeDeleted: includeDeleted},
            ),
            returnValue: _i13.Future<List<_i10.Transaction>>.value(
              <_i10.Transaction>[],
            ),
          )
          as _i13.Future<List<_i10.Transaction>>);

  @override
  _i13.Future<_i10.Transaction> updateTransaction(
    String? id, {
    _i15.Decimal? amount,
    _i16.TransactionType? type,
    String? shortDescription,
    _i2.Value<String?>? longDescription = const _i2.Value.absent(),
    DateTime? transactionDate,
    _i16.TransactionSource? source,
    String? currency,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateTransaction,
              [id],
              {
                #amount: amount,
                #type: type,
                #shortDescription: shortDescription,
                #longDescription: longDescription,
                #transactionDate: transactionDate,
                #source: source,
                #currency: currency,
              },
            ),
            returnValue: _i13.Future<_i10.Transaction>.value(
              _FakeTransaction_39(
                this,
                Invocation.method(
                  #updateTransaction,
                  [id],
                  {
                    #amount: amount,
                    #type: type,
                    #shortDescription: shortDescription,
                    #longDescription: longDescription,
                    #transactionDate: transactionDate,
                    #source: source,
                    #currency: currency,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i10.Transaction>);

  @override
  _i13.Future<void> softDeleteTransaction(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteTransaction, [id]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> hardDeleteTransaction(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#hardDeleteTransaction, [id]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> restoreTransaction(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#restoreTransaction, [id]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i10.TransactionCategoryMapData> assignCategory({
    required String? transactionId,
    required String? categoryId,
    required _i16.AssignmentSource? assignmentSource,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#assignCategory, [], {
              #transactionId: transactionId,
              #categoryId: categoryId,
              #assignmentSource: assignmentSource,
            }),
            returnValue: _i13.Future<_i10.TransactionCategoryMapData>.value(
              _FakeTransactionCategoryMapData_40(
                this,
                Invocation.method(#assignCategory, [], {
                  #transactionId: transactionId,
                  #categoryId: categoryId,
                  #assignmentSource: assignmentSource,
                }),
              ),
            ),
          )
          as _i13.Future<_i10.TransactionCategoryMapData>);

  @override
  _i13.Future<_i10.TransactionCategoryMapData?> getCategoryForTransaction(
    String? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCategoryForTransaction, [transactionId]),
            returnValue: _i13.Future<_i10.TransactionCategoryMapData?>.value(),
          )
          as _i13.Future<_i10.TransactionCategoryMapData?>);

  @override
  _i13.Future<List<_i10.TransactionCategoryMapData>> getTransactionsForCategory(
    String? categoryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsForCategory, [categoryId]),
            returnValue:
                _i13.Future<List<_i10.TransactionCategoryMapData>>.value(
                  <_i10.TransactionCategoryMapData>[],
                ),
          )
          as _i13.Future<List<_i10.TransactionCategoryMapData>>);

  @override
  _i13.Future<void> removeMapping(String? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#removeMapping, [transactionId]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<List<_i10.Transaction>> getTransactionsByCategory(
    String? categoryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsByCategory, [categoryId]),
            returnValue: _i13.Future<List<_i10.Transaction>>.value(
              <_i10.Transaction>[],
            ),
          )
          as _i13.Future<List<_i10.Transaction>>);

  @override
  _i13.Stream<T> createStream<T extends Object>(
    _i12.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i13.Stream<T>.empty(),
          )
          as _i13.Stream<T>);

  @override
  T alias<T, D>(_i2.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i14.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i2.TableInfo<_i2.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i2.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Stream<Set<_i2.TableUpdate>> tableUpdates([
    _i2.TableUpdateQuery? query = const _i2.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i13.Stream<Set<_i2.TableUpdate>>.empty(),
          )
          as _i13.Stream<Set<_i2.TableUpdate>>);

  @override
  _i13.Future<T> doWhenOpened<T>(
    _i13.FutureOr<T> Function(_i11.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i13.Future<T>.value(v),
                ) ??
                _FakeFuture_28<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i13.Future<T>);

  @override
  _i2.InsertStatement<T, D> into<T extends _i2.Table, D>(
    _i2.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_29<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i2.InsertStatement<T, D>);

  @override
  _i2.UpdateStatement<Tbl, R> update<Tbl extends _i2.Table, R>(
    _i2.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_30<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i2.UpdateStatement<Tbl, R>);

  @override
  _i2.SimpleSelectStatement<T, R> select<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_31<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i2.SimpleSelectStatement<T, R>);

  @override
  _i2.JoinedSelectStatement<T, R> selectOnly<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_32<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i2.JoinedSelectStatement<T, R>);

  @override
  _i2.BaseSelectStatement<_i2.TypedResult> selectExpressions(
    Iterable<_i2.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_33<_i2.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i2.BaseSelectStatement<_i2.TypedResult>);

  @override
  _i2.DeleteStatement<T, D> delete<T extends _i2.Table, D>(
    _i2.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_34<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i2.DeleteStatement<T, D>);

  @override
  _i13.Future<int> customUpdate(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i13.Future<int>.value(0),
          )
          as _i13.Future<int>);

  @override
  _i13.Future<int> customInsert(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i13.Future<int>.value(0),
          )
          as _i13.Future<int>);

  @override
  _i13.Future<List<_i2.QueryRow>> customWriteReturning(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i13.Future<List<_i2.QueryRow>>.value(
              <_i2.QueryRow>[],
            ),
          )
          as _i13.Future<List<_i2.QueryRow>>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelect(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_35<_i2.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i2.Selectable<_i2.QueryRow>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelectQuery(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_35<_i2.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i2.Selectable<_i2.QueryRow>);

  @override
  _i13.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<T> transaction<T>(
    _i13.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i13.Future<T>.value(v),
                ) ??
                _FakeFuture_28<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i13.Future<T>);

  @override
  _i13.Future<T> exclusively<T>(_i13.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i13.Future<T>.value(v),
                ) ??
                _FakeFuture_28<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i13.Future<T>);

  @override
  _i13.Future<void> batch(
    _i13.FutureOr<void> Function(_i2.Batch)? runInBatch,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<T> runWithInterceptor<T>(
    _i13.Future<T> Function()? action, {
    required _i2.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i13.Future<T>.value(v),
                ) ??
                _FakeFuture_28<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i13.Future<T>);

  @override
  _i2.GenerationContext $write(
    _i2.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_36(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i2.GenerationContext);

  @override
  _i2.GenerationContext $writeInsertable(
    _i2.TableInfo<_i2.Table, dynamic>? table,
    _i2.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_36(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i2.GenerationContext);

  @override
  _i2.GenerationContext $writeUpdateInsertable(
    _i2.TableInfo<_i2.Table, dynamic>? table,
    _i2.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeUpdateInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_36(
              this,
              Invocation.method(
                #$writeUpdateInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i2.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);

  @override
  _i13.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [CategoryDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryDao extends _i1.Mock implements _i3.CategoryDao {
  MockCategoryDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.AppDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeAppDatabase_37(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i10.AppDatabase);

  @override
  _i2.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_23(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i2.DatabaseConnection);

  @override
  _i2.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_20(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i2.DriftDatabaseOptions);

  @override
  _i2.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i14.dummyValue<_i2.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i2.SqlTypes);

  @override
  _i11.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_24(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i11.QueryExecutor);

  @override
  _i12.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_25(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i12.StreamQueryStore);

  @override
  _i2.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_26(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i2.DatabaseConnectionUser);

  @override
  _i10.$CategoriesTable get categories =>
      (super.noSuchMethod(
            Invocation.getter(#categories),
            returnValue: _Fake$CategoriesTable_9(
              this,
              Invocation.getter(#categories),
            ),
          )
          as _i10.$CategoriesTable);

  @override
  _i10.$CategoryClosureTable get categoryClosure =>
      (super.noSuchMethod(
            Invocation.getter(#categoryClosure),
            returnValue: _Fake$CategoryClosureTable_10(
              this,
              Invocation.getter(#categoryClosure),
            ),
          )
          as _i10.$CategoryClosureTable);

  @override
  _i10.$RecurringTransactionsTable get recurringTransactions =>
      (super.noSuchMethod(
            Invocation.getter(#recurringTransactions),
            returnValue: _Fake$RecurringTransactionsTable_11(
              this,
              Invocation.getter(#recurringTransactions),
            ),
          )
          as _i10.$RecurringTransactionsTable);

  @override
  _i10.$ImportsTable get imports =>
      (super.noSuchMethod(
            Invocation.getter(#imports),
            returnValue: _Fake$ImportsTable_12(
              this,
              Invocation.getter(#imports),
            ),
          )
          as _i10.$ImportsTable);

  @override
  _i10.$TransactionsTable get transactions =>
      (super.noSuchMethod(
            Invocation.getter(#transactions),
            returnValue: _Fake$TransactionsTable_13(
              this,
              Invocation.getter(#transactions),
            ),
          )
          as _i10.$TransactionsTable);

  @override
  _i10.$TransactionCategoryMapTable get transactionCategoryMap =>
      (super.noSuchMethod(
            Invocation.getter(#transactionCategoryMap),
            returnValue: _Fake$TransactionCategoryMapTable_14(
              this,
              Invocation.getter(#transactionCategoryMap),
            ),
          )
          as _i10.$TransactionCategoryMapTable);

  @override
  _i10.$BudgetTemplatesTable get budgetTemplates =>
      (super.noSuchMethod(
            Invocation.getter(#budgetTemplates),
            returnValue: _Fake$BudgetTemplatesTable_15(
              this,
              Invocation.getter(#budgetTemplates),
            ),
          )
          as _i10.$BudgetTemplatesTable);

  @override
  _i10.$BudgetPeriodsTable get budgetPeriods =>
      (super.noSuchMethod(
            Invocation.getter(#budgetPeriods),
            returnValue: _Fake$BudgetPeriodsTable_16(
              this,
              Invocation.getter(#budgetPeriods),
            ),
          )
          as _i10.$BudgetPeriodsTable);

  @override
  _i3.CategoryDaoManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _FakeCategoryDaoManager_41(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i3.CategoryDaoManager);

  @override
  _i13.Future<_i10.Category> insertCategory({
    required String? name,
    required _i16.CategoryType? type,
    _i17.IconData? icon,
    String? color,
    bool? isDefault = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertCategory, [], {
              #name: name,
              #type: type,
              #icon: icon,
              #color: color,
              #isDefault: isDefault,
            }),
            returnValue: _i13.Future<_i10.Category>.value(
              _FakeCategory_42(
                this,
                Invocation.method(#insertCategory, [], {
                  #name: name,
                  #type: type,
                  #icon: icon,
                  #color: color,
                  #isDefault: isDefault,
                }),
              ),
            ),
          )
          as _i13.Future<_i10.Category>);

  @override
  _i13.Future<_i10.Category?> getCategoryById(
    String? id, {
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCategoryById,
              [id],
              {#includeDeleted: includeDeleted},
            ),
            returnValue: _i13.Future<_i10.Category?>.value(),
          )
          as _i13.Future<_i10.Category?>);

  @override
  _i13.Future<List<_i10.Category>> getAllCategories({
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllCategories, [], {
              #includeDeleted: includeDeleted,
            }),
            returnValue: _i13.Future<List<_i10.Category>>.value(
              <_i10.Category>[],
            ),
          )
          as _i13.Future<List<_i10.Category>>);

  @override
  _i13.Future<List<_i10.Category>> getCategoriesByType(
    _i16.CategoryType? type, {
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCategoriesByType,
              [type],
              {#includeDeleted: includeDeleted},
            ),
            returnValue: _i13.Future<List<_i10.Category>>.value(
              <_i10.Category>[],
            ),
          )
          as _i13.Future<List<_i10.Category>>);

  @override
  _i13.Future<_i10.Category> updateCategory(
    String? id, {
    String? name,
    _i16.CategoryType? type,
    _i2.Value<_i17.IconData?>? icon = const _i2.Value.absent(),
    _i2.Value<String?>? color = const _i2.Value.absent(),
    bool? isDefault,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateCategory,
              [id],
              {
                #name: name,
                #type: type,
                #icon: icon,
                #color: color,
                #isDefault: isDefault,
              },
            ),
            returnValue: _i13.Future<_i10.Category>.value(
              _FakeCategory_42(
                this,
                Invocation.method(
                  #updateCategory,
                  [id],
                  {
                    #name: name,
                    #type: type,
                    #icon: icon,
                    #color: color,
                    #isDefault: isDefault,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i10.Category>);

  @override
  _i13.Future<void> softDeleteCategory(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteCategory, [id]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> hardDeleteCategory(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#hardDeleteCategory, [id]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> restoreCategory(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#restoreCategory, [id]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<List<_i10.Category>> getChildren(String? ancestorId) =>
      (super.noSuchMethod(
            Invocation.method(#getChildren, [ancestorId]),
            returnValue: _i13.Future<List<_i10.Category>>.value(
              <_i10.Category>[],
            ),
          )
          as _i13.Future<List<_i10.Category>>);

  @override
  _i13.Future<List<_i10.Category>> getDescendants(String? ancestorId) =>
      (super.noSuchMethod(
            Invocation.method(#getDescendants, [ancestorId]),
            returnValue: _i13.Future<List<_i10.Category>>.value(
              <_i10.Category>[],
            ),
          )
          as _i13.Future<List<_i10.Category>>);

  @override
  _i13.Future<void> moveCategory(String? categoryId, String? newParentId) =>
      (super.noSuchMethod(
            Invocation.method(#moveCategory, [categoryId, newParentId]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Stream<T> createStream<T extends Object>(
    _i12.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i13.Stream<T>.empty(),
          )
          as _i13.Stream<T>);

  @override
  T alias<T, D>(_i2.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i14.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i2.TableInfo<_i2.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i2.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Stream<Set<_i2.TableUpdate>> tableUpdates([
    _i2.TableUpdateQuery? query = const _i2.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i13.Stream<Set<_i2.TableUpdate>>.empty(),
          )
          as _i13.Stream<Set<_i2.TableUpdate>>);

  @override
  _i13.Future<T> doWhenOpened<T>(
    _i13.FutureOr<T> Function(_i11.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i13.Future<T>.value(v),
                ) ??
                _FakeFuture_28<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i13.Future<T>);

  @override
  _i2.InsertStatement<T, D> into<T extends _i2.Table, D>(
    _i2.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_29<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i2.InsertStatement<T, D>);

  @override
  _i2.UpdateStatement<Tbl, R> update<Tbl extends _i2.Table, R>(
    _i2.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_30<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i2.UpdateStatement<Tbl, R>);

  @override
  _i2.SimpleSelectStatement<T, R> select<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_31<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i2.SimpleSelectStatement<T, R>);

  @override
  _i2.JoinedSelectStatement<T, R> selectOnly<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_32<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i2.JoinedSelectStatement<T, R>);

  @override
  _i2.BaseSelectStatement<_i2.TypedResult> selectExpressions(
    Iterable<_i2.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_33<_i2.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i2.BaseSelectStatement<_i2.TypedResult>);

  @override
  _i2.DeleteStatement<T, D> delete<T extends _i2.Table, D>(
    _i2.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_34<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i2.DeleteStatement<T, D>);

  @override
  _i13.Future<int> customUpdate(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i13.Future<int>.value(0),
          )
          as _i13.Future<int>);

  @override
  _i13.Future<int> customInsert(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i13.Future<int>.value(0),
          )
          as _i13.Future<int>);

  @override
  _i13.Future<List<_i2.QueryRow>> customWriteReturning(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i13.Future<List<_i2.QueryRow>>.value(
              <_i2.QueryRow>[],
            ),
          )
          as _i13.Future<List<_i2.QueryRow>>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelect(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_35<_i2.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i2.Selectable<_i2.QueryRow>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelectQuery(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_35<_i2.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i2.Selectable<_i2.QueryRow>);

  @override
  _i13.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<T> transaction<T>(
    _i13.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i13.Future<T>.value(v),
                ) ??
                _FakeFuture_28<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i13.Future<T>);

  @override
  _i13.Future<T> exclusively<T>(_i13.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i13.Future<T>.value(v),
                ) ??
                _FakeFuture_28<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i13.Future<T>);

  @override
  _i13.Future<void> batch(
    _i13.FutureOr<void> Function(_i2.Batch)? runInBatch,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<T> runWithInterceptor<T>(
    _i13.Future<T> Function()? action, {
    required _i2.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i14.ifNotNull(
                  _i14.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i13.Future<T>.value(v),
                ) ??
                _FakeFuture_28<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i13.Future<T>);

  @override
  _i2.GenerationContext $write(
    _i2.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_36(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i2.GenerationContext);

  @override
  _i2.GenerationContext $writeInsertable(
    _i2.TableInfo<_i2.Table, dynamic>? table,
    _i2.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_36(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i2.GenerationContext);

  @override
  _i2.GenerationContext $writeUpdateInsertable(
    _i2.TableInfo<_i2.Table, dynamic>? table,
    _i2.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeUpdateInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_36(
              this,
              Invocation.method(
                #$writeUpdateInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i2.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);

  @override
  _i13.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}
