

class KeywordMapper {
    KeywordMapper.();


    static const Map<String, String> _rules = {

    'woolworths food': 'Groceries',
    'checkers': 'Groceries',
    'pick n pay': 'Groceries',
    'shoprite': 'Groceries',
    'spar': 'Groceries',
    'food lover': 'Groceries',
    'freshstop': 'Groceries',
    'cambridge food': 'Groceries',
    'boxer': 'Groceries',
    'ok foods': 'Groceries',
 
    'steers': 'Dining Out',
    'nando': 'Dining Out',
    'mcdonalds': 'Dining Out',
    'kfc': 'Dining Out',
    'debonairs': 'Dining Out',
    'pizza hut': 'Dining Out',
    'burger king': 'Dining Out',
    'wimpy': 'Dining Out',
    'restaurant': 'Dining Out',
    'cafe': 'Dining Out',
    'coffee': 'Dining Out',
    'starbucks': 'Dining Out',
    'ocean basket': 'Dining Out',
    'spur': 'Dining Out',
    'uber eats': 'Dining Out',
    'mr delivery': 'Dining Out',
    'bolt food': 'Dining Out',
 
    'uber': 'Transport',
    'bolt': 'Transport',
    'indriver': 'Transport',
    'taxi': 'Transport',
    'fuel': 'Transport',
    'engen': 'Transport',
    'shell': 'Transport',
    'bp ': 'Transport',
    'total ': 'Transport',
    'caltex': 'Transport',
    'sasol': 'Transport',
    'e-toll': 'Transport',
    'sanral': 'Transport',
    'metrobus': 'Transport',
    'golden arrow': 'Transport',
    'myciti': 'Transport',
    'parking': 'Transport',
 
    'eskom': 'Utilities',
    'city power': 'Utilities',
    'electricity': 'Utilities',
    'water': 'Utilities',
    'rates': 'Utilities',
    'telkom': 'Utilities',
    'rain ': 'Utilities',
    'mtn airtime': 'Utilities',
    'vodacom': 'Utilities',
    'cell c': 'Utilities',
    'prepaid': 'Utilities',
 
    'netflix': 'Subscriptions',
    'showmax': 'Subscriptions',
    'dstv': 'Subscriptions',
    'spotify': 'Subscriptions',
    'apple': 'Subscriptions',
    'google play': 'Subscriptions',
    'microsoft': 'Subscriptions',
    'amazon prime': 'Subscriptions',
    'youtube premium': 'Subscriptions',
    'canva': 'Subscriptions',
    'chatgpt': 'Subscriptions',
    'openai': 'Subscriptions',
    'subscription': 'Subscriptions',
    'monthly fee': 'Subscriptions',
 
    'dischem': 'Health & Medical',
    'clicks pharmacy': 'Health & Medical',
    'pharmacy': 'Health & Medical',
    'hospital': 'Health & Medical',
    'doctor': 'Health & Medical',
    'dentist': 'Health & Medical',
    'optometrist': 'Health & Medical',
    'medical aid': 'Health & Medical',
    'discovery health': 'Health & Medical',
    'momentum health': 'Health & Medical',
    'bonitas': 'Health & Medical',
    'medihelp': 'Health & Medical',
 
    'woolworths': 'Clothing',
    'mr price': 'Clothing',
    'edgars': 'Clothing',
    'truworths': 'Clothing',
    'foschini': 'Clothing',
    'jet store': 'Clothing',
    'identity': 'Clothing',
    'cotton on': 'Clothing',
    'zara': 'Clothing',
    'h&m': 'Clothing',
    'pep stores': 'Clothing',
    'ackermans': 'Clothing',
 
    'ster-kinekor': 'Entertainment',
    'nu metro': 'Entertainment',
    'silverstar': 'Entertainment',
    'grandwest': 'Entertainment',
    'sun city': 'Entertainment',
    'ticket': 'Entertainment',
    'concert': 'Entertainment',
    'event': 'Entertainment',
    'takealot': 'Entertainment',
    'gaming': 'Entertainment',
    'playstation': 'Entertainment',
    'xbox': 'Entertainment',
    'steam': 'Entertainment',
 
    'university': 'Education',
    'college': 'Education',
    'tuition': 'Education',
    'school fee': 'Education',
    'udemy': 'Education',
    'coursera': 'Education',
    'skillshare': 'Education',
    'books': 'Education',
    'stationery': 'Education',
 
    'salon': 'Personal Care',
    'barber': 'Personal Care',
    'spa': 'Personal Care',
    'beauty': 'Personal Care',
    'clicks': 'Personal Care',
    'dis-chem': 'Personal Care',
 
    'builders': 'Home & Maintenance',
    'leroy merlin': 'Home & Maintenance',
    'hardware': 'Home & Maintenance',
    'plumber': 'Home & Maintenance',
    'electrician': 'Home & Maintenance',
    'garden': 'Home & Maintenance',
    'furniture': 'Home & Maintenance',
    'ikea': 'Home & Maintenance',
    '@home': 'Home & Maintenance',
 
    'flight': 'Travel',
    'airlink': 'Travel',
    'fastjet': 'Travel',
    'kulula': 'Travel',
    'flysafair': 'Travel',
    'comair': 'Travel',
    'hotel': 'Travel',
    'airbnb': 'Travel',
    'booking.com': 'Travel',
    'car hire': 'Travel',
    'avis': 'Travel',
    'budget car': 'Travel',
 
    'rent': 'Rent',
    'lease': 'Rent',
    'rental': 'Rent',
 
    'gift': 'Gifts & Donations',
    'donation': 'Gifts & Donations',
    'npo': 'Gifts & Donations',
    'charity': 'Gifts & Donations',
 
    'salary': 'Salary',
    'payroll': 'Salary',
    'wages': 'Salary',
    'remuneration': 'Salary',
    'nett pay': 'Salary',
    'net pay': 'Salary',
 
    'freelance': 'Freelance',
    'invoice': 'Freelance',
    'consulting': 'Freelance',
    'contract payment': 'Freelance',
 
    'dividend': 'Investments',
    'interest': 'Investments',
    'investment': 'Investments',
    'return': 'Investments',
    'capital gain': 'Investments',
    'unit trust': 'Investments',
    'easy equities': 'Investments',
    'satrix': 'Investments', 

    //got these mappings/matches from AI - 
    };

    static String? classify(String description) {
        final lower = description.toLowerCase();
        for ( final  entry in  _rules.entries) {
            if ( lower.contains(entry.key)) {
                return entry.value;
            }
        }
        return null;
    }
}